update automation

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -50,6 +50,12 @@ jobs:
           # Uses grep with a Perl-compatible regex to find the version string
           # inside the 'const VERSION' line in the specified file and sets it as an output variable.
           VERSION=$(grep -oP "const VERSION = '\K[^']+" ${{ env.VERSION_FILE }})
+
+          if [ -z "$VERSION" ]; then
+            echo "::error::Could not find the version number in ${{ env.VERSION_FILE }}"
+            exit 1
+          fi
+
           echo "version=${VERSION}" >> $GITHUB_OUTPUT
 
       # 4. Creates a Git Tag and a GitHub Release using the extracted version
